//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class COPDPSQuestionAnswer
    {
        public int Id { get; set; }
        public string Answer { get; set; }
        public int COPDPSQuestionId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> points { get; set; }
    
        public virtual COPDPSQuestion COPDPSQuestion { get; set; }
    }
}
