//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEV1Staging
    {
        public int Id { get; set; }
        public string Stage { get; set; }
        public string Text { get; set; }
        public bool IsActive { get; set; }
    }
}
