//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.PatientInvestigations = new HashSet<PatientInvestigation>();
            this.PatientMedicalHistories = new HashSet<PatientMedicalHistory>();
            this.PatientMHCatScores = new HashSet<PatientMHCatScore>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TitleId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> MaritialStatusId { get; set; }
        public string Mobile { get; set; }
        public string NIC { get; set; }
        public string Occupation { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string Designation { get; set; }
        public string EmergencyContactName { get; set; }
        public string EmergencyContactNo { get; set; }
        public string ClinicDays { get; set; }
        public string ClinicTime { get; set; }
        public string CodePrefix { get; set; }
        public Nullable<int> CodeNumber { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual MaritialStatu MaritialStatu { get; set; }
        public virtual Title Title { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientInvestigation> PatientInvestigations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientMedicalHistory> PatientMedicalHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientMHCatScore> PatientMHCatScores { get; set; }
    }
}
