//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientMedicalHistory
    {
        public int Id { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> DyspnoeaId { get; set; }
        public Nullable<int> mMRCGradeId { get; set; }
        public string CATScore { get; set; }
        public string NoOfExacerbationPerLastYear { get; set; }
        public string ComorbidityId { get; set; }
        public string ComorbidityOthers { get; set; }
        public Nullable<int> SmokingHistoryId { get; set; }
        public Nullable<System.DateTime> SHDateStopped { get; set; }
        public string SHSmokedADay { get; set; }
        public string SHNoOfYearsSmoked { get; set; }
        public string SHPackYears { get; set; }
        public string ETS { get; set; }
        public string SubstanceAbuse { get; set; }
        public string BiomassFuelSmokeExposure { get; set; }
        public string OccupationAtPresent { get; set; }
        public string PreviousOccupations { get; set; }
        public string FamilyHistoryId { get; set; }
        public string FamilyHistoryOthers { get; set; }
        public string AllergicHistoryDrugs { get; set; }
        public string AllergicHistoryOthers { get; set; }
        public string MedicationHistoryCOPD { get; set; }
        public string MedicationHistoryNonCOPD { get; set; }
        public string VaccinationHistoryId { get; set; }
        public string ComplicationId { get; set; }
        public string ComplicationOther { get; set; }
        public string PhysicalExaminationId { get; set; }
        public string BMI { get; set; }
        public Nullable<int> JugularVenousPulseId { get; set; }
        public string PulseRate { get; set; }
        public string BloodPressure { get; set; }
        public string CardiacAuscultationA2P2 { get; set; }
        public string CardiacAuscultationS1 { get; set; }
        public string PulmonaryAucscultation { get; set; }
        public Nullable<int> ExacerbationHistoryId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual mMRCGrade mMRCGrade { get; set; }
        public virtual SmokingHistory SmokingHistory { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
